#!/bin/bash

####################################################################################
#AUTHOR: Clement Deltel
#COMPANY: TmaxSoft
#SCRIPT: oframe_script_folders_gen
#DATE: 2019/11/12
#DESCRIPTION: This script's purpose is to create multiple folders for scripts non 
#             automatically generated by OF installation.
####################################################################################

# If you have the following error running this script:
# syntax error near unexpected token `$'{\r''
#
# Run first the command: dos2unix oframe_script_folders_gen.sh

####################################################################################
#FUNCTION: folder_generation
#DESCRIPTION: generate multiple useful folder, for custom scripts for instance, that
#             are not generated by OpenFrame installation.
#
# NOTICE: Feel free to add new folders if necessary for your environement.
####################################################################################
folder_generation(){
  output_file=$1

  echo "
##############################################################################
#                   SCRIPTS FOLDERS                                          #
##############################################################################" >> $output_file
  # OpenFrame
  if [ ! -d $OPENFRAME_HOME/scripts/custom ]
  then
    mkdir $OPENFRAME_HOME/scripts/custom
    echo 'export PATH=$OPENFRAME_HOME/scripts/custom:$PATH' >> $output_file
    echo "scripts/custom folder in OPENFRAME_HOME generated!"
  else
    echo "The folder already exist!"
  fi

  # JEUS 7
  if [ ! -d $JEUS_HOME/scripts ]
  then
    mkdir $JEUS_HOME/scripts
    echo 'export PATH=$JEUS_HOME/scripts:$PATH' >> $output_file
    echo "scripts folder in JEUS_HOME (jeus7) generated!"
  else
    echo "The folder already exist!"
  fi
  
  . ~/.bash_profile
  echo "Please run the command echo \$PATH. If it is not up to date, please execute the bash profile"
}

####################################################################################
#FUNCTION : main
####################################################################################
main(){
  folder_generation ~/.bash_profile
  cp -rT $HOME_DIRECTORY/tmaxsw/scripts/jeus/jeus7 $JEUS_HOME/scripts
  cp -rT $HOME_DIRECTORY/tmaxsw/scripts/openframe $OPENFRAME_HOME/scripts/custom
}
main
